//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int visit_ID { get; set; }
        public System.DateTime date { get; set; }
        public int fee { get; set; }
        public string drug { get; set; }
        public string complaint { get; set; }
        public int patient_ID { get; set; }
        public string pulse { get; set; }
        public Nullable<double> temp { get; set; }
        public string bloodpressure { get; set; }
        public string general { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
